require 'stringio'
require 'uri'
require 'open-uri'
require 'net/dav'
require 'highline/import'

require 'open-uri-and-write/handle'
require 'open-uri-and-write/usernames'
require 'open-uri-and-write/credentials_store'
require 'open-uri-and-write/file_extensions'
require 'open-uri-and-write/dir_extensions'
require 'open-uri-and-write/kernel_extensions'
